### ISSUE TITLE
Max-target-seqs and evalue parameters (v2.5)

### ISSUE THREAD

**Issue by OKersten** [blobtoolkit/insdc-pipeline#11]
Hi 

I was wondering about the max-target-seqs and evalue parameter for diamond blastp, diamond blastx, and blastn megablast.
Is this parameter 10 (max-target-seqs) and 1.0e-25 (evalue) for all of them? 

Cheers,
Oliver

**Comment by rjchallis** [comment]
Yes, these parameters are the defaults across all of the blasts. The pipeline can use different cutoff values for running and importing so the blast can be run at 1e-10 then imported at 1e-25, for example in case you want to test the effect of different cutoff values.

The blastn/blastx results can be imported with `--hit-count` set to the same value as max_target_seqs, but for the blast taxrule things are a little different as max target sees refers to the number of hits per gene, but `--hit-count` refers to number of hits across all genes on a scaffold so setting this to a very high number ensures that all of the hits to genes on a scaffold are imported.

**Comment by OKersten** [comment]
Thanks for the super fast response. 
I am not 100% sure I understand what you exactly mean in the second paragraph.

Are you saying that one COULD set `--hit-count` to the same value as `max_target_seqs` but should actually set it to a very high number instead (e.g. 10000) which ensures that all of the hits to genes on a scaffold are imported?

**Comment by rjchallis** [comment]
Sorry I missed this earlier. For the blastp taxrule, the scaffold is treated as a single unit rather than broken into chunks. If you only want to include the top 10 hits across the scaffold then yes, you could set `--hit-count` to 10, but the high number lets you import all hits.
