### ISSUE TITLE
Extract_busco_genes and chunk_fasta (v2.5)

### ISSUE THREAD

**Issue by OKersten** [blobtoolkit/insdc-pipeline#12]
Hi 

I am trying to set up the entire blobtools pipeline without snakemake (I know, actually somewhat pointless), and pretty much got it all to work. 
Yet, I was wondering about extract_busco_genes.py in the diamond_blastp sub-pipeline and chunk_fasta.py in the diamond_blastx pipeline.

extract_busco_genes.py only accepts one busco "full_table.tsv.gz", correct? So is there a merging step in the diamond_blastp pipeline which combines hits of all 3 basal lineages into 1 single fasta for subsequent analyses?

Similarily, chunk_fasta.py only accepts one busco "full_table.tsv.gz", correct? In order to split the long contigs into chunks
containing busco genes, does one only run it for one specific lineage or is there also some merging going on that combines results of various different lineages and then allows splitting based on gene density?

Thanks for any tips and clarification.

Cheers,
Oliver

**Comment by rjchallis** [comment]
Great to hear that you are trying to run the pipeline without snakemake! I tried to set things up so everything could be run independently so at least now I know that someone is making use of it.

For `extract_busco_genes.py`, the`...` in `[--busco PATH...]` means that you can repeat this flag in the command, so you can run it on all 3 lineages in one command like `extract_busco_genes.py --busco eukaryota.tsv --busco bacteria.tsv --busco archaea.tsv`. 

`chunk_fasta.py` does only accept one lineage (the pipeline uses the first lineage in the config file array). This should be the most specific lineage to ensure the maximum number of busco containing regions can be extracted. It would be possible to concatenate `full_table.tsv` files for multiple lineages (the `.gz` is optional) to use more than one lineage in this step.

Finally I should add that I'm expecting to get v2.6 released later this week and then I'll be hoping to keep the pipeline stable for a long time. It is similar enough to 2.5 that your efforts so far with 2.5 will be worthwhile but makes better use of windowed statistics to allow inspection of patterns of variables along chromosomes in the Viewer. Most of the scripts have stayed the same, but there are a couple of extra steps to allow first splitting everything into 1kb chunks for calculating gc, coverage, etc then averaging across these in various window sizes.

**Comment by OKersten** [comment]
Great to hear and thanks for the clarification!

Looking forward to v2.6!!
