### ISSUE TITLE
[v2.6.1] BUSCO "KeyError" 'download_dir'

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/insdc-pipeline#16]
Alrighty, the pipeline has progressed but is throwing the following error when it gets to the BUSCO step:

```
cat blobtoolkit/logs/busco/run_sub_pipeline.log

Creating specified working directory /gscratch/scrubbed/samwhite/outputs/20210712_pgen_blobtools_Panopea-generosa-v1.0/busco.
KeyError in line 10 of /gscratch/srlab/programs/blobtoolkit-v2.6.1/pipeline/rules/run_busco5.smk:
'download_dir'
  File "/gscratch/srlab/programs/blobtoolkit-v2.6.1/pipeline/busco.smk", line 44, in <module>
  File "/gscratch/srlab/programs/blobtoolkit-v2.6.1/pipeline/rules/run_busco5.smk", line 10, in <module>
```

The error message doesn't reveal too much info to me. Any ideas on what's happening and/or what I can do to address this?

If you need my full script, I can post it.

**Comment by rjchallis** [comment]
Sorry about this one - I changed the BUSCO command to run in offline mode, which means it now needs the full busco data from https://busco-data.ezlab.org/v5/data to run, and the lineages sit in a subdirectory of this. I changed the key in the busco section of the config from `lineage_dir` to `download_dir` to reflect this and forgot that to would break older configs. So the fix will be to make sure you have the full busco data, with any lineages unpacked, e.g. using:
```
BUSCO=/volumes/databases/busco_2021_06
cd $BUSCO
wget -r https://busco-data.ezlab.org/v5/data
find busco-data.ezlab.org -name "*.tar.gz" | parallel "cd {//}; tar -xzf {/}"
```
then update your config to:
```
busco:
  download_dir: /volumes/databases/busco_2021_06
  lineages:
    ...
```

**Comment by kubu4** [comment]
Thanks.

To clarify, where should lineage dbs be located?

`$BUSCO`

or

`$BUSCO/busco-data.ezlab.org`

or

`$BUSCO/busco-data.ezlab.org/v5/data/`

EDITED: Added additional location.

**Comment by kubu4** [comment]
Actually, I just realized that the `wget -r https://busco-data.ezlab.org/v5/data` command wasn't successful. It didn't download recursively and spit out the following error(s) for each of the subdirectories in that URL:

```shell
Connecting to busco-data.ezlab.org (busco-data.ezlab.org)|129.194.190.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
busco-data.ezlab.org/v5/data/lineages: Not a directorybusco-data.ezlab.org/v5/data/lineages/index.html: Not a directory

Cannot write to ‘busco-data.ezlab.org/v5/data/lineages/index.html’ (Success).
```

**Comment by kubu4** [comment]
Ignore my previous comment! I tried again and things are downloading as expected!

**Comment by kubu4** [comment]
Suggested changes resolved this error. Thanks.

**Comment by kubu4** [comment]
Just want to add this for posterity. The directory structure that's downloaded using `wget -r https://busco-data.ezlab.org/v5/data` isn't set up properly for BUSCO.

After downloading, the `lineages` directory needs to be moved here:

`$BUSCO/lineages`
