### ISSUE TITLE
chunk_fasta.py "fails" when running outside of snakemake

### ISSUE THREAD

**Issue by OKersten** [blobtoolkit/insdc-pipeline#18]
Hi,

I am running the blobtools pipeline outside of snakemake manually step-by-step. After upgrading from v2.5 to 2.6+ the `chunk_fasta.py` fails due to an error on line 329
`if seq["length"] >= args["--min-length"]:`

This is due to comparison between integer and string.

I changed line 329 to
`if seq["length"] >= int(args["--min-length"]):`

and the script now works and the fasta is now chunked.

Cheers

**Comment by rjchallis** [comment]
Thanks for letting me know about this - I've committed the fix so it will be in the next release
