### ISSUE TITLE
Downloading uniprot databse

### ISSUE THREAD

**Issue by Glenn032787** [blobtoolkit/insdc-pipeline#23]
Hi, I am stuck in the diamond blastn section of the pipeline. I have tried manually downloading it using the script in the Github page but wget seem to not finish downloading (stops at 100GB) resulting the un-taring the file to have EOF error. On the website, it mentioned that the database will be fetched or generated if it doesn't exist. How do I change the config file to download it automatically?

Thank you!

**Comment by sujaikumar** [comment]
Hi - are you talking about this bit on https://github.com/blobtoolkit/blobtoolkit/tree/main/src/btk_pipeline#databases

Download and extract UniProt reference proteomes
```
UNIPROT=/volumes/databases/uniprot_2021_06
mkdir -p $UNIPROT
wget -q -O $UNIPROT/reference_proteomes.tar.gz \
 ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/$(curl \
     -vs ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/ 2>&1 | \
     awk '/tar.gz/ {print $9}')
cd $UNIPROT
tar xf reference_proteomes.tar.gz
```

We have also found that sometimes wget fails (or takes very long) when downloading large files from ftp.ebi.ac.uk

One possibility is to just try again at a different time.

The other possibility is to use a specialist tool like aria2 for downloading large files
```
## install using conda:
# conda install -c bioconda aria2
## install using apt:
# sudo apt install -y aria2

aria2c --max-connection-per-server=4 ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/Reference_Proteomes_2022_01.tar.gz 
tar xzf Reference_Proteomes_2022_01.tar.gz
```
and then process the rest of the steps as above.

**Comment by Glenn032787** [comment]
Thank you aira2 worked a lot better!

**Comment by bricoletc** [comment]
I had issues with the EBI ftp for the latest version: Reference_Proteomes_2023_02
wget completed, but untarring failed (EOF), several times

Using the expasy ftp from Switzerland instead was both much faster (~10x speed from France) and untarring completed successfully: 

```
wget -q -O $UNIPROT_dir/reference_proteomes.tar.gz \
    https://ftp.expasy.org/databases/uniprot/current_release/knowledgebase/reference_proteomes/Reference_Proteomes_2023_02.tar.gz
```

**Comment by sujaikumar** [comment]
Thanks @bricoletc - added to [README](https://github.com/blobtoolkit/pipeline#databases)
