### ISSUE TITLE
Documentation: No snake_env in install instructions

### ISSUE THREAD

**Issue by kubu4** [blobtoolkit/insdc-pipeline#7]
The [installation documentation](https://blobtoolkit.genomehubs.org/install/) only mentions creating a conda environment called `btk_env`. An environment called `snake_env` is not mentioned.

However, the [Running the Pipeline documentation](https://blobtoolkit.genomehubs.org/pipeline/pipeline-tutorials/running-the-pipeline/) says to activate the conda environment `snake_env`.

Is the `btk_env` environment the same as the `snake_env` environment (i.e. should we use the `btk_env` when running the pipeline)?

**Comment by rjchallis** [comment]
The btk_env in the install instructions is an example of how to install the dependencies if not using the pipeline and snake_env in the example is just intended to be an environment that contains snakemake. Snakemake could be added to the btk_env but this environment doesn't need to have any other btk dependencies as these can be installed automatically by snakemake with the --use-conda flag.

**Comment by kubu4** [comment]
Thanks for the clarification on this. I get it now. I didn't realize that the `btk_env` _didn't_ automatically set up a Snakemake environment.

**Comment by DianaOaxaca** [comment]
Hi, I´m sorry but its doesn´t clear to me. 
how create snake_env and run pipeline with local assemblies?
Thanks for everything

**Comment by kubu4** [comment]
@DianaOaxaca here's a basic outline of the steps needed:

1. Follow the [blobtools installation instructions](https://blobtoolkit.genomehubs.org/install/).

2. Deactivate your conda `btk_env` environment:

`conda deactivate`

3. Install Mamba (per the SnakeMake instructions):

`conda install -n base -c conda-forge mamba`

4. Activate your conda `btk_env`:

`conda activate btk_env`

5. Follow the rest of the [SnakeMake Full Installation instructions](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html#full-installation).

This procedure will install SnakeMake in your conda `btk_env`. Then, when you want to run any of the blobtoolkit pipeline, you'll activate your conda `btk_env` and you'll now have access to SnakeMake as well.
